project:
  type: book 
  output-dir: _output

book:
  title: "Interval Forecasting of Cryptocurrency Returns using Quantile Regression Forests: An Application to the Solana Ecosystem"
  author: "James Lewis"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_literature.qmd
    - 03_data_features.qmd
    - 04_methods.qmd
    - 05_results.qmd
    - 06_trading.qmd
    - 07_discussion.qmd
    - 08_conclusion.qmd
  appendices:  
    - appendices/A1_data_appendix.qmd
    - appendices/A2_models_appendix.qmd
    - appendices/A3_results_appendix.qmd
    - appendices/A4_extras_appendix.qmd
    - appendices/A5_code_appendix.qmd


format:
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    include-before-body: [cover.tex, toc.tex]
    header-includes:
      - \usepackage{graphicx}             
      - \AtBeginDocument{\renewcommand{\maketitle}{}}
    default-image-extension: pdf
    toc: true
    papersize: a4
    number-sections: true
    geometry: [margin=1in]
    fig-cap-location: bottom
    tbl-cap-location: top
    df-print: default
    link-citations: true
    keep-tex: true

bibliography: references.bib
csl: csl/harvard.csl

execute:
  echo: false
  warning: false
  message: false
  cache: false      # set true only if you add live chunks and want caching
